$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
command: >
  python train.py
environment: azureml:sklearn-1.1:36
inputs:
    training_data:
      type: uri_folder 
      path: azureml:attrition_data:1
compute: azureml:cpu-cluster
experiment_name: employee_attrition_experiment